# Generated by Django 3.2 on 2021-11-28 06:36

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20211128_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ppt',
            field=models.FileField(blank=True, upload_to=Users.models.save_homework_files, verbose_name='Presentations'),
        ),
    ]
