# Generated by Django 3.2 on 2021-11-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_task_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='no-slug', max_length=200),
        ),
    ]
