# Generated by Django 3.2 on 2021-11-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0009_auto_20211128_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Student', max_length=12),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to=settings.AUTH_USER_MODEL),
        ),
    ]
